/** API pública del módulo proscenio (stage). */

export {
  parseStage,
  StageBlockSchema,
  StageExitSchema,
  MAX_STAGE_EXITS,
  type StageBlock,
  type StageExit,
  type ParseStageResult,
} from "./schema.js";
export {
  scaleAt,
  stageToView,
  viewToStage,
  worldToStage,
  stageToWorld,
  type StageProjParams,
  type StageBounds,
} from "./projection.js";
export {
  composeStageScene,
  type ComposedStage,
  type ComposedStageExit,
  type StageItem,
} from "./scene.js";
export { stageToViewAt } from "./projection.js";
export {
  buildGreyboxSpec,
  expectedElementsFromGreybox,
  canonicalGreyboxJson,
  STAGE_GREYBOX_VERSION,
  GREYBOX_EYE_M,
  type GreyboxSpec,
  type GreyboxPrimitive,
  type GreyboxLight,
  type GreyboxCamera,
  type GreyboxManifestItem,
  type StageScenePlan,
} from "./greybox.js";
export { stagePlanFromScene } from "./plan.js";
export {
  buildPeelPrompt,
  STAGE_PEEL_VERSION,
  pxToView,
  calibratedProjection,
  contactToPose,
  footprintFromContact,
  matchInventory,
  peelStepsFromInventory,
  collisionGridFromCutouts,
  reconstructionDiff,
  fitSpriteScale,
  spriteScaleAt,
  SPRITE_SCALE_IDENTITY,
  type SpriteScaleModel,
  type SpriteScalePoint,
  STAGE_RENDER_SIZE,
  RECONSTRUCTION_DEFAULTS,
  type StageExpectedElement,
  type StageReviewItem,
  type PaintedFloor,
  type CutoutPose,
  type InventoryMatch,
  type InventoryPeelStep,
  type CollisionCutout,
  type StageCollisionResult,
  type ReconstructionReport,
} from "./segments.js";
export {
  frameStage,
  parallaxPanX,
  viewToScreen,
  viewToScreenCam,
  layerRectCam,
  sCamAt,
  camRatio,
  maxDollyFor,
  bandPlanFor,
  bandDestRect,
  bandPlanDestRects,
  FRAMING_DEFAULTS,
  BAND_PLAN_DEFAULTS,
  STAGE_CAM_ZERO,
  MAX_NEAR_ZOOM,
  type StageCam,
  type StageFraming,
  type FramingOpts,
  type ViewBoxRect,
  type GroundBand,
  type BandPlan,
  type BandPlanOpts,
} from "./framing.js";
export {
  railCamera,
  stageFollow,
  FOLLOW_X,
  FOLLOW_Z,
  type RailCameraOpts,
  type StageFollowOpts,
} from "./camera.js";
export { exitZoneAt, spawnPointForEntry } from "./entry.js";
