import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { z } from 'zod';
import { WsBridge } from './ws-bridge.js';

async function main() {
  const bridge = await WsBridge.create();

  const server = new McpServer({
    name: 'narrative',
    version: '1.0.0',
  });

  // Stored request_id and kind from the last listen call, so respond knows where to send
  let currentRequestId: string | null = null;
  let currentKind: 'room' | 'weapon_orient' | 'weapon_verify' | 'narrative_event' = 'room';

  server.tool(
    'narrative_listen',
    `Block until the Python AI server sends a generation request.

The returned content has a "kind" field indicating the request type:

==== kind: "room" (or missing) ====
You are the narrative engine for a Godot 4 dark fantasy RPG.
All units in METERS. Room centered at origin, floor at y=0.

When you receive a world state with entry_wall, generate this JSON structure
and call narrative_respond with the JSON:
{
  "room_id": "unique_id",
  "room_description": "2-3 sentences in Spanish",
  "dimensions": { "width": 8-15, "height": 3-5, "depth": 8-15 },
  "surfaces": { "floor": {...}, "ceiling": {...}, "walls": [...] },
  "exits": [{ "wall": "south", "offset": 0, "size": [2,3], ... }],
  "lighting": { "ambient": {...}, "lights": [...] },
  "objects": [...],
  "npcs": [...],
  "ambient_event": "atmospheric text in Spanish"
}
RULES: exit on entry_wall, objects.y=0 floor, descriptions in Spanish, prompts in English.

==== kind: "weapon_orient" ====
You are looking at 3 orthographic renders of an isolated 3D weapon mesh
(front, side, top — in that order) generated by the AI 3D pipeline.

The mesh is centered on its bounding box. Coordinates you return are
NORMALIZED to [0,1]^3 where (0,0,0) is bbox min and (1,1,1) is bbox max.

The 3 view conventions:
- front: camera at +Z looking toward origin (X right, Y up)
- side:  camera at +X looking toward origin (Z right, Y up)
- top:   camera at +Y looking down (X right, -Z into screen)

Identify:
1. grip_point_normalized — where the hand wraps the weapon
   (cylindrical wrapped area for swords; center of back face for shields;
    bottom of haft for axes/maces; middle of riser for bows)
2. blade_direction — unit vector from grip toward tip/edge/front
3. up_direction — unit vector perpendicular to blade_direction, the "up" face
   (back of sword blade, front of shield, top of axe head)

Right-handed coordinates throughout. All vectors must be unit length.
Confidence: 0.9+ if grip and blade are clearly visible; 0.5-0.8 if uncertain;
<0.5 if the mesh looks broken or you cannot identify the weapon.

Respond with narrative_respond, passing this JSON:
{
  "grip_point_normalized": [x, y, z],
  "blade_direction":       [x, y, z],
  "up_direction":          [x, y, z],
  "weapon_type":           "sword" | "shield" | "axe" | "mace" | "staff" | "bow" | "dagger" | "spear" | "generic",
  "grip_length_normalized": 0.0..1.0,
  "confidence":             0.0..1.0,
  "notes":                  "short rationale"
}

==== kind: "weapon_verify" ====
You see one image of a character holding a weapon. Verify the weapon is
correctly placed in the hand for combat stance. Respond:
{ "ok": bool, "issue": "string", "suggested_delta_euler": [rx, ry, rz] }

==== kind: "narrative_event" ====
A player has just answered an NPC. You receive: speaker, chosen_text,
free_text, and a context snapshot of the NarrativeState (story_so_far,
recent_dialogues, entities already in the world, current scene id,
available_assets).

CRITICAL — when free_text is non-empty:
- The scripted scenario is PAUSED waiting for you. You MUST respond with at
  least one \`dialogue\` consequence so a visible NPC reacts in-world and the
  player sees something happen. Stay in character for the setting.
- Write the dialogue text in the SAME LANGUAGE the player used in free_text
  (Spanish for Spanish, English for English, etc.).
- The dialogue \`speaker\` should be an NPC already in \`entities\` — reuse
  the same display name so the game can route the line to them. It can be
  the speaker you received or another NPC present in the scene.
- If the player expressed intent to go somewhere or find something
  (forge, healer, captain), also add a spawn_entity consequence and have
  the dialogue reference the newly-spawned thing.

CRITICAL — when free_text is empty (numbered choice only):
- The scripted scenario advances on its own. Usually return an empty
  consequences array unless the choice strongly implies a world reaction.

Respond with narrative_respond, passing this JSON:
{
  "consequences": [
    { "type": "dialogue", "speaker": "NPC display name",
      "text": "what they say (same language as free_text)",
      "choices": ["optional", "2-3 follow-up", "options"] },
    { "type": "story_update", "delta": "1-3 sentences appended to story_so_far" },
    { "type": "spawn_entity", "entity_kind": "npc"|"building"|"object",
      "description": "vivid English description for asset gen",
      "name": "optional NPC name", "position_hint": "near_player|distant_east|...",
      "texture_hash": "optional reused asset hash",
      "model_hash": "optional reused asset hash" },
    { "type": "schedule_event", "description": "what to schedule",
      "trigger": "next_scene|timer:60s|on_player_action:..." }
  ]
}
Max 4 consequences. Reuse available_assets by hash when sensible.`,
    {},
    async () => {
      try {
        const msg = await bridge.waitForRequest();
        currentRequestId = msg.request_id;

        if (msg.type === 'vision_request') {
          currentKind = msg.kind;
          // Build content blocks: text header + image blocks + footer
          const header = JSON.stringify({
            kind: msg.kind,
            weapon_type: msg.weapon_type,
            context: msg.context ?? {},
            num_images: msg.images.length,
          }, null, 2);

          // deno-lint-ignore no-explicit-any
          const content: any[] = [
            { type: 'text', text: `Vision request:\n${header}` },
          ];
          for (const img of msg.images) {
            content.push({
              type: 'image',
              data: img.data_b64,
              mimeType: img.media_type,
            });
            content.push({ type: 'text', text: `(view: ${img.view})` });
          }
          content.push({
            type: 'text',
            text: 'Examine the views and call narrative_respond with the JSON described in the tool docs.',
          });
          return { content };
        }

        if (msg.type === 'narrative_event') {
          currentKind = 'narrative_event';
          const payload = JSON.stringify({
            kind: 'narrative_event',
            event_kind: msg.kind,
            event_id: msg.event_id,
            speaker: msg.speaker,
            chosen_text: msg.chosen_text,
            free_text: msg.free_text,
            context: msg.context,
          }, null, 2);
          return {
            content: [{
              type: 'text',
              text: `Narrative event:\n${payload}\n\nDecide consequences and call narrative_respond with the JSON described in the tool docs (kind: narrative_event).`,
            }],
          };
        }

        // room_request
        currentKind = 'room';
        return {
          content: [{
            type: 'text',
            text: JSON.stringify({ kind: 'room', world_state: msg.world_state }, null, 2),
          }],
        };
      } catch (e) {
        return { content: [{ type: 'text', text: (e as Error).message }], isError: true };
      }
    },
  );

  server.tool(
    'narrative_respond',
    'Send the response back to the Python AI server. Must be called after narrative_listen. ' +
    'The room_data field accepts a JSON string with the room data OR the vision result, ' +
    'depending on the kind of the most recent listen request.',
    {
      room_data: z.string().describe('JSON string. For kind=room: full room data. For kind=weapon_orient: { grip_point_normalized, blade_direction, up_direction, weapon_type, confidence, ... }'),
    },
    async ({ room_data }) => {
      try {
        if (!currentRequestId) {
          return { content: [{ type: 'text', text: 'No pending request. Call narrative_listen first.' }], isError: true };
        }

        const parsed = JSON.parse(room_data);
        const reqId = currentRequestId;
        const kind = currentKind;
        currentRequestId = null;
        currentKind = 'room';

        if (kind === 'weapon_orient' || kind === 'weapon_verify') {
          bridge.sendVisionResponse(reqId, parsed);
          return { content: [{ type: 'text', text: `Vision response sent for request ${reqId}` }] };
        }

        if (kind === 'narrative_event') {
          bridge.sendNarrativeEventResponse(reqId, parsed);
          return { content: [{ type: 'text', text: `Narrative event response sent for request ${reqId}` }] };
        }

        bridge.sendResponse(reqId, parsed);
        return { content: [{ type: 'text', text: `Room sent for request ${reqId}` }] };
      } catch (e) {
        return { content: [{ type: 'text', text: (e as Error).message }], isError: true };
      }
    },
  );

  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error('[narrative-mcp] MCP server running on stdio');
}

main().catch((e) => {
  console.error('[narrative-mcp] Fatal:', e);
  process.exit(1);
});
