/** Runtime config — single source of truth for which features are active.
 *
 * Rule of the house: if a feature is `true`, it must be available and must
 * work; if it's `false`, any code path that depends on it MUST refuse to run
 * (throw, not silently fall back). No half-states, no placeholders.
 *
 * Imported as `CONFIG` from anywhere in `nefan-core`, `nefan-html`, and the
 * bridge. `ai_server` / `narrative-mcp` read the JSON snapshot generated by
 * `scripts/dump-config.ts` from `data/runtime_config.json`.
 */

export interface NefanConfig {
  graphics: {
    /** Pre-rendered Mixamo sprite sheets on disk for the player. When false,
     *  the player is drawn as a coloured circle and no sheets are loaded. */
    player_sprites: boolean;
    /** img2img AI skin pass on top of the Mixamo sheet via ai_server's
     *  /skin_sprite_sheet endpoint. Requires player_sprites = true. */
    ai_skin: boolean;
    /** AI 2D sprites for entities via /generate_sprite (asset-cache). */
    ai_sprites: boolean;
    /** AI PBR textures for objects via /generate_texture. */
    ai_textures: boolean;
    /** AI GLB models for objects/buildings via /generate_model. */
    ai_models: boolean;
  };
  narrative: {
    /** Demand a live narrative listener (a second Claude Code session that
     *  called `narrative_listen`). If false, the only-LLM rule is relaxed —
     *  but there is no scripted fallback either, so the game just refuses to
     *  start. Default true. */
    require_llm: boolean;
    /** Reject LLM consequence aliases (show_dialogue→dialogue, text→delta).
     *  When true, the validator throws on aliases; when false it tolerates
     *  them. Default true. */
    strict_validator: boolean;
  };
  session: {
    /** Demand a live bridge (ws://localhost:9877 + http://localhost:9878).
     *  When true and the bridge is down, the game refuses to start. Default
     *  true. There is no `LocalGameClient` fallback any more. */
    require_bridge: boolean;
  };
}

export const CONFIG: NefanConfig = {
  graphics: {
    player_sprites: false,
    ai_skin: false,
    ai_sprites: false,
    ai_textures: false,
    ai_models: false,
  },
  narrative: {
    require_llm: true,
    strict_validator: true,
  },
  session: {
    require_bridge: true,
  },
};
