/** Runtime config — single source of truth for which features are active.
 *
 * Rule of the house: if a feature is `true`, it must be available and must
 * work; if it's `false`, any code path that depends on it MUST refuse to run
 * (throw, not silently fall back). No half-states, no placeholders.
 *
 * Imported as `CONFIG` from anywhere in `nefan-core`, `nefan-html`, and the
 * bridge. `ai_server` / `narrative-mcp` read the JSON snapshot generated by
 * `scripts/dump-config.ts` from `data/runtime_config.json`.
 */

export interface NefanConfig {
  graphics: {
    /** Pre-rendered Mixamo sprite sheets on disk for ALL characters (player,
     *  NPCs, enemies). When true, the y_bot base set is mandatory (missing
     *  sheets are a hard error at startup); per-entity AI skins are an async
     *  upgrade on top. When false, characters are drawn as coloured circles
     *  and no sheets are loaded. */
    character_sprites: boolean;
    /** img2img AI skin pass on top of the y_bot sheet via ai_server's
     *  /skin_sprite_sheet endpoint, driven by each entity's narrative
     *  description. Requires character_sprites = true. ai_server being down
     *  degrades to the y_bot base (one error-log entry, no retry loop). */
    ai_skin: boolean;
    /** AI 2D sprites for entities via /generate_sprite (asset-cache). */
    ai_sprites: boolean;
    /** AI PBR textures for objects via /generate_texture. */
    ai_textures: boolean;
    /** AI GLB models for objects/buildings via /generate_model. */
    ai_models: boolean;
  };
  narrative: {
    /** Demand a live narrative listener (a second Claude Code session that
     *  called `narrative_listen`). If false, the only-LLM rule is relaxed —
     *  but there is no scripted fallback either, so the game just refuses to
     *  start. Default true. */
    require_llm: boolean;
    /** Reject LLM consequence aliases (show_dialogue→dialogue, text→delta).
     *  When true, the validator throws on aliases; when false it tolerates
     *  them. Default true. */
    strict_validator: boolean;
  };
  session: {
    /** Demand a live bridge (ws://localhost:9877 + http://localhost:9878).
     *  When true and the bridge is down, the game refuses to start. Default
     *  true. There is no `LocalGameClient` fallback any more. */
    require_bridge: boolean;
  };
  /** Knobs only meant for development. Production should leave these off. */
  dev: {
    /** Cache the bootstrap of a fresh session (world map + first scene) by
     *  gameId. When true and a cache entry exists for `start_session`'s
     *  gameId, the bridge replays it instead of asking the narrative engine,
     *  saving the ~90 s the LLM spends on the initial bootstrap. Cache lives
     *  in `nefan-core/data/initial_scene_cache/` (gitignored); delete the
     *  file (or the dir) to invalidate. */
    cache_initial_scene: boolean;
  };
  /** Python ai_server runtime. Lives here so there is exactly one config
   *  file in the repo; `scripts/dump-config.ts` emits the snapshot the
   *  server reads at startup. Fail-loud: a missing field is a hard error,
   *  not a `.get(key, default)` silent fallback. */
  ai_server: {
    llm_model: string;
    llm_timeout_s: number;
    port: number;
    cache_root: string;
    texture_cache_dir: string;
    model_cache_dir: string;
    skin_cache_dir: string;
    sprite_cache_dir: string;
    /** Cache for full-scene img2img backgrounds + outpainted extensions,
     *  served at /cache/scene/{hash}. */
    scene_cache_dir: string;
    /** Cache for occluder sprites cut out of the scene image (SAM via fal.ai),
     *  served at /cache/segment/{hash}. */
    segment_cache_dir: string;
    texture_resolution: number;
    texture_steps: number;
    /** Meshy image-to-image model for scene generation (best top-down:
     *  nano-banana-pro). Also valid: nano-banana, nano-banana-2, gpt-image-2. */
    scene_model: string;
    /** Meshy image-to-image model for character sprite skinning (hero-shot +
     *  atlas de keyframes por anim×dir — pipeline validado en skinning_lab;
     *  la vía local SD1.5+ControlNet quedó descartada por deriva). */
    sprite_skin_model: string;
    /** Path (relative to repo root) of the art-style reference image passed as
     *  the 2nd reference to Meshy so generated scenes match a target game look. */
    scene_style_image: string;
    /** fal.ai SAM2 auto-segment model id: segmentación automática completa de
     *  la escena pintada (mundo derivado de imagen). Needs FAL_KEY. */
    auto_segment_model: string;
    texture_lazy_load: boolean;
    /** Mount the /diagnostic/* router (skin_test_* endpoints used for manual
     *  parameter sweeps with curl). Off in production: the routes 404. */
    expose_diagnostic: boolean;
    /** Techo del cache de assets en bytes. Al arrancar (y vía POST
     *  /cache/prune) se evictan los assets menos usados (LRU por `last_used`
     *  del manifest) hasta bajar del límite. 0 = sin límite. */
    cache_max_bytes: number;
  };
  /** Puertos del stack — fuente única. Los consumidores TS importan CONFIG;
   *  los servicios no-TS (narrative-mcp, ai_server) leen el snapshot
   *  runtime_config.json. Las env vars de cada servicio siguen mandando como
   *  override (NEFAN_BRIDGE_PORT, NARRATIVE_WS_PORT…). El puerto HTTP del
   *  ai_server vive en su propio bloque (ai_server.port). */
  ports: {
    /** WebSocket bridge de nefan-core (ws-server.ts). */
    bridge: number;
    /** State HTTP API del bridge (tools del motor narrativo). */
    state_api: number;
    /** WebSocket del narrative-mcp (ai_server ↔ motor). */
    narrative_ws: number;
    /** Remote control TCP de Godot (testing automatizado). */
    godot_remote: number;
    /** Vite dev server del cliente HTML 2D. */
    html: number;
  };
  /** Contenido de juego compartido entre bridge y ai_server (paths relativos
   *  a la raíz del repo). El bridge los usa para listar/arrancar juegos; el
   *  ai_server, para resolver los style packs (imágenes de referencia). */
  content: {
    /** data/games — un dir por juego (game.json + world.md + plugins/). */
    games_dir: string;
    /** data/styles — un dir por estilo (style.json + imágenes de referencia). */
    styles_dir: string;
  };
}

export const CONFIG: NefanConfig = {
  graphics: {
    character_sprites: true,
    ai_skin: true,
    ai_sprites: false,
    ai_textures: false,
    ai_models: false,
  },
  narrative: {
    require_llm: true,
    strict_validator: true,
  },
  session: {
    require_bridge: true,
  },
  dev: {
    cache_initial_scene: false,
  },
  ai_server: {
    llm_model: "claude-sonnet-4-5-20250514",
    // El bootstrap del formato de plan (mapa del mundo + map_ground +
    // volumes) puede tardar >5 min en escribirse con Claude Code Max.
    llm_timeout_s: 900,
    port: 8765,
    cache_root: "cache",
    texture_cache_dir: "cache/textures",
    model_cache_dir: "cache/models",
    skin_cache_dir: "cache/skins",
    sprite_cache_dir: "cache/sprites",
    scene_cache_dir: "cache/scenes",
    segment_cache_dir: "cache/segments",
    texture_resolution: 512,
    texture_steps: 4,
    scene_model: "nano-banana-pro",
    sprite_skin_model: "nano-banana-2",
    scene_style_image: "skinning_lab/bases/battlemap-town-style.png",
    auto_segment_model: "fal-ai/sam2/auto-segment",
    texture_lazy_load: true,
    expose_diagnostic: false,
    cache_max_bytes: 2 * 1024 * 1024 * 1024, // 2 GiB
  },
  ports: {
    bridge: 9877,
    state_api: 9878,
    narrative_ws: 3737,
    godot_remote: 9876,
    html: 3000,
  },
  content: {
    games_dir: "nefan-core/data/games",
    styles_dir: "nefan-core/data/styles",
  },
};
