/** Runtime config — single source of truth for which features are active.
 *
 * Rule of the house: if a feature is `true`, it must be available and must
 * work; if it's `false`, any code path that depends on it MUST refuse to run
 * (throw, not silently fall back). No half-states, no placeholders.
 *
 * Imported as `CONFIG` from anywhere in `nefan-core`, `nefan-html`, and the
 * bridge. `ai_server` / `narrative-mcp` read the JSON snapshot generated by
 * `scripts/dump-config.ts` from `data/runtime_config.json`.
 *
 * Los puertos de SERVICIOS no se declaran aquí: la fuente única es
 * `contracts/service-registry.ts` (SERVICES) y `CONFIG.ports` los DERIVA.
 * Aquí solo viven los puertos que no son servicios del registro (sidecar
 * MCP, dev server HTML).
 */
import { SERVICES } from "./contracts/service-registry.js";

export interface NefanConfig {
  graphics: {
    /** Pre-rendered Mixamo sprite sheets on disk for ALL characters (player,
     *  NPCs, enemies). When true, the y_bot base set is mandatory (missing
     *  sheets are a hard error at startup); per-entity AI skins are an async
     *  upgrade on top. When false, characters are drawn as coloured circles
     *  and no sheets are loaded. */
    character_sprites: boolean;
    /** img2img AI skin pass on top of the y_bot sheet via ai_server's
     *  /skin_sprite_sheet endpoint, driven by each entity's narrative
     *  description. Requires character_sprites = true. ai_server being down
     *  degrades to the y_bot base (one error-log entry, no retry loop).
     *  OFF by default: cada anim son varias llamadas Meshy (créditos reales);
     *  con false todos los personajes usan la base y_bot. */
    ai_skin: boolean;
    /** PROHIBIDO — no reintroducir nunca un modo de recorte por siluetas
     *  DECLARADAS (el extinto `image_analysis: "masks"`): rasterizar el plan
     *  del motor como máscara sobre la imagen pintada se probó y NO funciona
     *  — el modelo de imagen recoloca y reorienta lo declarado, la máscara
     *  recorta SUELO con forma de objeto y el objeto real queda cocido en la
     *  placa. Jamás va a funcionar. Si algún día vuelve a hacer falta un
     *  recorte, se deriva SIEMPRE segmentando lo que el modelo PINTÓ; el plan
     *  declarado solo sirve de pista. */
  };
  narrative: {
    /** Demand a live narrative listener (a second Claude Code session that
     *  called `narrative_listen`). If false, the only-LLM rule is relaxed —
     *  but there is no scripted fallback either, so the game just refuses to
     *  start. Default true. */
    require_llm: boolean;
    /** Reject LLM consequence aliases (show_dialogue→dialogue, text→delta).
     *  When true, the validator throws on aliases; when false it tolerates
     *  them. Default true. */
    strict_validator: boolean;
  };
  session: {
    /** Demand a live bridge (ws://localhost:9877 + http://localhost:9878).
     *  When true and the bridge is down, the game refuses to start. Default
     *  true. There is no `LocalGameClient` fallback any more. */
    require_bridge: boolean;
  };
  /** Python ai_server runtime. Lives here so there is exactly one config
   *  file in the repo; `scripts/dump-config.ts` emits the snapshot the
   *  server reads at startup. Fail-loud: a missing field is a hard error,
   *  not a `.get(key, default)` silent fallback. */
  ai_server: {
    llm_model: string;
    llm_timeout_s: number;
    port: number;
    cache_root: string;
    /** Librería de celdas de superficie de la vista fps (kind "surface"),
     *  servida en /cache/surface/{hash}. Es el ÚNICO directorio de blobs del
     *  asset-store desde #257: los seis caches históricos sin productor
     *  (texturas, modelos, skins, sprites, repintados, recortes SAM2) se
     *  archivaron en archivo/cache/ y sus filas se purgaron del índice. */
    surface_cache_dir: string;
    /** Modelo image-to-image con el que sprite-forge viste a los personajes
     *  (hero-shot de identidad + atlas de keyframes por anim×dir). */
    sprite_skin_model: string;
    /** Dónde escucha **sprite-forge**, el servicio de hojas de sprites de
     *  personaje. Vive en su propio repo (~/code/sprite-forge) porque lo usa
     *  más de un proyecto: ne-fan es UN consumidor suyo, no su dueño. Si no
     *  está arriba, /skin_sprite_sheet devuelve 503 diciendo a qué URL
     *  intentó llamar, y el cliente degrada a la hoja base. */
    sprite_forge_url: string;
    /** Modelos del atlas de superficies de la vista fps (bench labs/fps):
     *  tileables (surface_model) y celdas hero (surface_hero_model), fal
     *  directo. */
    surface_model: string;
    surface_hero_model: string;
    /** Tasa fija USD→EUR para el contador de gasto del panel de dev (los
     *  precios de Meshy/fal son USD; el cliente muestra euros). */
    usd_eur_rate: number;
    /** Techo del cache de assets en bytes. Al arrancar (y vía POST
     *  /cache/prune) se evictan los assets menos usados (LRU por `last_used`
     *  del manifest) hasta bajar del límite. 0 = sin límite. */
    cache_max_bytes: number;
    /** Índice SQLite del asset-store (F2) — sustituye a cache/manifest.json
     *  (que se conserva congelado como referencia/rollback). Relativo a la
     *  raíz del repo, como el resto de rutas de cache. */
    manifest_db: string;
  };
  /** Puertos del stack — fuente única. Los consumidores TS importan CONFIG;
   *  los servicios no-TS (narrative-mcp, ai_server) leen el snapshot
   *  runtime_config.json. Las env vars de cada servicio siguen mandando como
   *  override (NEFAN_BRIDGE_PORT, NARRATIVE_WS_PORT…). El puerto HTTP del
   *  ai_server vive en su propio bloque (ai_server.port). */
  ports: {
    /** WebSocket bridge de nefan-core (ws-server.ts). */
    bridge: number;
    /** State HTTP API del bridge (tools del motor narrativo). */
    state_api: number;
    /** WebSocket del narrative-mcp (ai_server ↔ motor). */
    narrative_ws: number;
    /** HTTP del ai_server (S3 narrative-llm). Mismo número que
     *  `ai_server.port`, que es el que lee el Python: aquí está para que el
     *  bloque de puertos del stack esté COMPLETO en un solo sitio — `start.sh`
     *  los lee todos de aquí y ya no declara ninguno. */
    ai_server: number;
    /** Vite dev server del cliente HTML 2D. */
    html: number;
    /** asset-store (S6): blobs content-addressed + manifest SQLite (F2). */
    asset_store: number;
    /** remote-gen (S5): adaptador Meshy/fal — repintados, sheets, SAM2 (F4). */
    remote_gen: number;
    /** fake-ai-server (labs/narrative): emula S3–S6 con 0 créditos. No es un
     *  servicio del registro —no existe en producción— pero SÍ es un puerto
     *  del stack que arranca `start.sh` y que el bench de QA necesita citar.
     *  Estaba escrito a mano en `start.sh` y en `qa/run.mjs`, y esa constante
     *  duplicada era lo único que protegía de verdad al guardarraíl de gasto. */
    fake_ai: number;
    /** sprite-forge: hojas de sprites de personaje. Vive en OTRO repo, así que
     *  aquí solo se declara DÓNDE se le pide que escuche (`--port`). */
    sprite_forge: number;
    /** API de control del emulador de juego (`labs/narrative/game-emulator.mjs`):
     *  el bench narrativo se conduce con curl contra ella. No lo arranca
     *  `start.sh`, pero es un puerto del stack igual, y estaba escrito a mano
     *  en el único sitio donde la regla `nadie-inventa-un-puerto` no miraba —
     *  el décimo servicio entrando solo por la puerta de atrás. */
    game_emulator: number;
  };
  /** Contenido de juego compartido entre bridge y ai_server (paths relativos
   *  a la raíz del repo). El bridge los usa para listar/arrancar juegos; el
   *  ai_server, para resolver los style packs (imágenes de referencia). */
  content: {
    /** data/games — un dir por juego (game.json + world.md + plugins/). */
    games_dir: string;
    /** data/styles — un dir por estilo (style.json + imágenes de referencia). */
    styles_dir: string;
  };
}

/** Puertos que NO son servicios del registro y que, aun así, forman parte del
 *  stack que arranca `start.sh`. Se declaran aquí arriba porque los consume
 *  más de un campo del objeto de abajo (`sprite_forge_url` deriva del suyo) y
 *  porque un literal repetido dentro del mismo fichero es la primera grieta
 *  por la que un puerto se vuelve a escribir a mano en otro sitio. */
const PORT_NARRATIVE_WS = 3737;
const PORT_HTML = 3000;
const PORT_FAKE_AI = 18765;
const PORT_SPRITE_FORGE = 8770;
const PORT_GAME_EMULATOR = 9899;

export const CONFIG: NefanConfig = {
  graphics: {
    character_sprites: true,
    // Backend de skins disponible: el gate de GASTO es el modo runtime de la
    // faceta personajes (world.character_mode, toggle del menú dev). Sin
    // MESHY_API_KEY el endpoint responde 503 y el cliente degrada a y_bot.
    ai_skin: true,
  },
  narrative: {
    require_llm: true,
    strict_validator: true,
  },
  session: {
    require_bridge: true,
  },
  ai_server: {
    llm_model: "claude-sonnet-4-5-20250929",
    // El bootstrap del formato de plan (mapa del mundo + ground +
    // volumes) puede tardar >5 min en escribirse con Claude Code Max.
    llm_timeout_s: 1800,
    port: SERVICES["narrative-llm"].currentPort,
    cache_root: "cache",
    surface_cache_dir: "cache/surfaces",
    sprite_skin_model: "gpt-image-2",
    sprite_forge_url: `http://127.0.0.1:${PORT_SPRITE_FORGE}`,
    // Atlas de superficies de la vista fps (bench labs/fps): nano-banana-pro
    // para las celdas tileables (cohesión pintada a mano) y gpt-image-2 para
    // las celdas hero (techo de calidad en piezas únicas).
    surface_model: "nano-banana-pro",
    surface_hero_model: "gpt-image-2",

    usd_eur_rate: 0.86,
    cache_max_bytes: 2 * 1024 * 1024 * 1024, // 2 GiB
    manifest_db: "cache/manifest.sqlite3",
  },
  ports: {
    bridge: SERVICES["game-gateway"].currentPort,
    state_api: SERVICES["world-state"].currentPort,
    narrative_ws: PORT_NARRATIVE_WS,
    ai_server: SERVICES["narrative-llm"].currentPort,
    html: PORT_HTML,
    asset_store: SERVICES["asset-store"].currentPort,
    remote_gen: SERVICES["remote-gen"].currentPort,
    fake_ai: PORT_FAKE_AI,
    sprite_forge: PORT_SPRITE_FORGE,
    game_emulator: PORT_GAME_EMULATOR,
  },
  content: {
    games_dir: "nefan-core/data/games",
    styles_dir: "nefan-core/data/styles",
  },
};
